server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  tomcat:
    threads:
      max: 200
      min: 10
management:
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: "*"
        exclude: shutdown

resilience4j.ratelimiter:
  instances:
    apiRateLimiter:
      limit-for-period: 5
      limit-refresh-period: 10s
      timeout-duration: 0
resilience4j.circuitbreaker:
  instances:
    apiCircuitBreaker:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3
      sliding-window-type: count_based
      sliding-window-size: 10

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    user: postgres


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
#spring:
#  security:
#    user:
#      name: admin
#      password: admin